baseURL = "https://miraieagent.co.jp/"
languageCode = "ja"
copyright = "&copy; Miraieagent Inc."
title = "Miraieagent Inc."
theme = "hugo-fresh"

[params]
  description = "株式会社ミライヘ"
  date_format = "2016-01-02"

[permalinks]
  post = "/:year/:month/:title/"
